
<div class="p-3">

    <table
            class="table"
            id="itemLister"
            data-toggle="table"
            data-show-columns="true"
            data-search="true"
            data-show-toggle="true"
            data-pagination="true"
            data-resizable="true"
            data-sortable="true"
            <?php
                if(sizeof($view->items) == 0 ){
                    echo "data-url='/json/data.json'";
                }
            ?>
    >
        <thead>
            <tr>
                <th data-checkbox="true"></th>
                <?php
                    foreach($view->fields as $field){
                        if(in_array($field, $view->defaultFields)){
                            echo "<th data-field='$field' scope='col' data-sortable='true'>$field</th>";
                        }else {
                            echo "<th data-field='$field' scope='col' data-sortable='true' data-visible='false'>$field</th>";
                        }
                    }
                ?>
            </tr>
        </thead>
        <tbody>
        <?php
            foreach($view->items as $item){
                echo "<tr><td data-checkbox='false'></td>";
                $itemData = $item->getDbRow();
                foreach($view->fields as $field){
                    echo "<td>" . $itemData[$field] . "</td>";
                }
                echo "</tr>";
            }
        ?>
        </tbody>
    </table>
</div>
</div>
<?php require_once $_SERVER['DOCUMENT_ROOT'] . "/views/template/footer.phtml";
