<div class="row justify-content-start mx-5">
    <?php
    if(sizeof($view->items) == 0) {
        if(!isset($_SESSION['jsonFile'])) {
            $json = file_get_contents($_SERVER['DOCUMENT_ROOT'] . '/json/data.json');
            $_SESSION['jsonFile'] = json_decode($json, true);
        }
        $view->items = $_SESSION['jsonFile'];
    }
    $counter = 0;
    foreach($view->items as $item){
        $counter += 1;
        if($counter >= 50){
            break;
        }
        echo "
            <div class='card m-3' style='width: 20rem'><div class='card-body app'>";
        foreach($view->defaultFields as $field){
            if($field == 'appid'){
                echo "<h5 class='card-title app-id'><span style='font-weight: bold'>App ID:</span> " . $item[$field] ." </h5>";
            }else{
                echo "<p><span style='font-weight: bold'>$field:</span> " . $item[$field] ."</p>";
            }
        }
        echo "<div class='d-flex'><input type='checkbox' class='form-check-input'><p class='mx-2'>Select Item</p></div><button href='' class='btn btn-dark dsp-btn'>More Details</button>
    </div></div>";
    }
    ?>
</div>

<!-- item details view Modal  -->
<div class="modal fade" id="itemDetailsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel"><span style="font-weight: bold">Game Details</span></h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
               <div class="details-view-data">

               </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>

