<div class="col-10 p-0 overflow-auto" style="background-color: #EEEEEE">

    <nav class="navbar navbar-expand-lg navbar-light bg-light pt-0 pb-0" >
        <div class="container-fluid" style="background-color: #D4D4D4">

            <a class="navbar-brand" href="#"><img src="../images/Add-Energy-Logo.png" width="60" height="60" alt="logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <div class="col-8">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle bg-dark text-white rounded-pill" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Select User Type
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Proofreader</a></li>
                            <li><a class="dropdown-item" href="#">Salesperson</a></li>
                            <li><a class="dropdown-item" href="#">Developer</a></li>
                            <li><a class="dropdown-item" href="#">Data analyst</a></li>
                        </ul>
                    </li>
                </ul>
               </div>
                <form action=<?php echo $_SERVER['PHP_SELF']; ?> method="post">
                    <div class="input-group">
                        <input type="search" class="form-control bg-dark text-white" placeholder="Search.." name="mainSearch" aria-label="Recipient's username" aria-describedby="button-addon2">
                            <button class="btn btn-outline-secondary bg-dark" type="submit" id="button-addon2"><i class="bi bi-search text-white"></i>
                            </button>
                    </div>
                </form>
            </div>
        </div>
    </nav>




