<div class="col-10 p-0">
<!--<nav class="navbar navbar-expand-sm navbar-dark">
    <div class="container-fluid">

    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <li class="nav-item dropdown">
                <button class="nav-link dropdown-toggle" href="#" id="dropbtn" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Select User Type
                </button>
                <ul class="dropdown-menu dropdown-content" aria-labelledby="dropbtn">

                </ul>
            </li>
            <form class="top-search-button" >
                <input type="text" placeholder="Search.." name="search..">
                <button type="submit"><i class="fa fa-search"></i></button>
            </form>
        </ul>
    </div>
</nav>-->

    <nav class="navbar navbar-expand-lg navbar-light bg-light pt-0" >
        <div class="container-fluid" style="background-color: #D4D4D4">
            <a class="navbar-brand" href="#"><img src="../images/Add-Energy-Logo.png" width="60" height="60" alt="logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <div class="col-8">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle bg-dark text-white rounded-pill" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Select User Type
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
               </div>
                <div class="input-group">
                    <input type="text" class="form-control bg-dark text-white" placeholder="Search.." name="search.." aria-label="Recipient's username" aria-describedby="button-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary bg-dark" type="submit" id="button-addon2"><i class="bi bi-search text-white"></i>
                        </button>
                    </div>
                </div>

            </div>
        </div>
    </nav>
<?php require_once $_SERVER['DOCUMENT_ROOT'] . "/views/itemLister.phtml";




