
<div class="p-3">
    <div class="position-relative">
        <nav class="navbar navbar-light bg-light fixed-top" style="width:130px;"> <!--The style can be removed or changed to suit the position-->
            <div class="container-fluid">
                <button class="btn btn-outline-dark" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"><i class="bi bi-funnel-fill"></i>Filters</button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Filter by:</h5>
                        <button type="button" class="btn-close text-reset" style="width:25px; height:25px; background-color:red" data-bs-dismiss="offcanvas" aria-label="Close"></button>

                    </div><br><br>

                    <div id="wrapper">
                        <div id="sliderContainer">
                            <div class="tick-slider">
                                <div class="tick-slider-header">
                                    <h5><label for="priceSlider">Price range (£):</label></h5>
                                </div>
                                <div class="tick-slider-value-container">
                                    <div id="priceLabelMin" class="tick-slider-label">0</div>
                                    <div id="priceLabelMax" class="tick-slider-label">100</div>
                                    <div id="priceValue" class="tick-slider-value"></div>
                                </div>
                                <div class="tick-slider-background"></div>
                                <div id="priceProgress" class="tick-slider-progress"></div>
                                <div id="priceTicks" class="tick-slider-tick-container"></div>
                                <input
                                    id="range"
                                    class="tick-slider-input"
                                    type="range"
                                    min="0"
                                    max="100"
                                    step="1"
                                    value="50"
                                    data-tick-step="5"
                                    data-tick-id="priceTicks"
                                    data-value-id="priceValue"
                                    data-progress-id="priceProgress"
                                    data-handle-size="18"
                                    data-min-label-id="priceLabelMin"
                                    data-max-label-id="priceLabelMax"
                                />
                            </div>
                            <div class="tick-slider">
                                <div class="tick-slider-header">
                                    <h5><label for="positiveSlider">Positive Rating:</label></h5>
                                </div>
                                <div class="tick-slider-value-container">
                                    <div id="positiveLabelMin" class="tick-slider-label">0</div>
                                    <div id="positiveLabelMax" class="tick-slider-label">3000000</div>
                                    <div id="positiveValue" class="tick-slider-value"></div>
                                </div>
                                <div class="tick-slider-background"></div>
                                <div id="positiveProgress" class="tick-slider-progress"></div>
                                <div id="positiveTicks" class="tick-slider-tick-container"></div>
                                <input
                                    id="range"
                                    class="tick-slider-input"
                                    type="range"
                                    min="0"
                                    max="3000000"
                                    step="10000"
                                    value="500000"
                                    data-tick-step="15"
                                    data-tick-id="positiveTicks"
                                    data-value-id="positiveValue"
                                    data-progress-id="positiveProgress"
                                    data-handle-size="18"
                                    data-min-label-id="positiveLabelMin"
                                    data-max-label-id="positiveLabelMax"
                                />
                            </div><br>

                            <div class="tick-slider">
                                <div class="tick-slider-header">
                                    <h5><label for="negativeSlider">Negative Rating:</label></h5>
                                </div>
                                <div class="tick-slider-value-container">
                                    <div id="negativeLabelMin" class="tick-slider-label">0</div>
                                    <div id="negativeLabelMax" class="tick-slider-label">300</div>
                                    <div id="negativeValue" class="tick-slider-value"></div>
                                </div>
                                <div class="tick-slider-background"></div>
                                <div id="negativeProgress" class="tick-slider-progress"></div>
                                <div id="negativeTicks" class="tick-slider-tick-container"></div>
                                <input
                                    id="range"
                                    class="tick-slider-input"
                                    type="range"
                                    min="0"
                                    max="3000000"
                                    step="10000"
                                    value="300000"
                                    data-tick-step="15"
                                    data-tick-id="negativeTicks"
                                    data-value-id="negativeValue"
                                    data-progress-id="negativeProgress"
                                    data-handle-size="18"
                                    data-min-label-id="negativeLabelMin"
                                    data-max-label-id="negativeLabelMax"
                                />
                            </div><br>

                            <div class="tick-slider">
                                <div class="tick-slider-header">
                                    <h5><label for="unitsSoldSlider">Units Sold:</label></h5>
                                </div>
                                <div class="tick-slider-value-container">
                                    <div id="unitsSoldLabelMin" class="tick-slider-label">0</div>
                                    <div id="unitsSoldLabelMax" class="tick-slider-label">300</div>
                                    <div id="unitsSoldValue" class="tick-slider-value"></div>
                                </div>
                                <div class="tick-slider-background"></div>
                                <div id="unitsSoldProgress" class="tick-slider-progress"></div>
                                <div id="unitsSoldTicks" class="tick-slider-tick-container"></div>
                                <input
                                    id="range"
                                    class="tick-slider-input"
                                    type="range"
                                    min="0"
                                    max="3000000"
                                    step="10000"
                                    value="0"
                                    data-tick-step="15"
                                    data-tick-id="unitsSoldTicks"
                                    data-value-id="unitsSoldValue"
                                    data-progress-id="unitsSoldProgress"
                                    data-handle-size="18"
                                    data-min-label-id="unitsSoldLabelMin"
                                    data-max-label-id="unitsSoldLabelMax"
                                />
                            </div>
                            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                                <li class="nav-item dropdown">  <!--Top 10 Developers dropdown-->
                                    <h6 class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Top 10 Developers:</h6>
                                    <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                                        <hr class="dropdown-divider">
                                        </li>
                                        <li><a class="dropdown-item" href="#">Choice of Games</a></li> <!--the links not added-->
                                        <li><a class="dropdown-item" href="#">KOEI TECMO GAMES CO., LTD.</a></li>
                                        <li><a class="dropdown-item" href="#">Ripknot Systems</a></li>
                                        <li><a class="dropdown-item" href="#">Laush Dmitriy Sergeevich</a></li>
                                        <li><a class="dropdown-item" href="#">Nikita "Ghost_RUS"</a></li>
                                        <li><a class="dropdown-item" href="#">Dexion Games</a></li>
                                        <li><a class="dropdown-item" href="#">RewindApp</a></li>
                                        <li><a class="dropdown-item" href="#">Hosted Games</a></li>
                                        <li><a class="dropdown-item" href="#">Blender Games</a></li>
                                        <li><a class="dropdown-item" href="#">Humongous Entertainment</a></li>
                                    </ul>
                                </li><br>
                                <li> <!--Release Date calendar-->
                                    <form>
                                        <h6>Release Date:</h6>
                                        <p>From:</p>
                                        <input type="date" id="date" name="from-date">
                                        <p>To:</p>
                                        <input type="date" id="date" name="to-date">
                                    </form>
                                </li><br>
                                <li><br><br>
                                    <div class="position-relative"> <!--The submit button-->
                                        <button type="submit" class="btn btn-primary position-absolute top-0 start-50 translate-middle" style="width: 30%;">Submit</button>
                                    </div>
                                </li>
                            </ul>

                        </div>
                    </div>


                </div>
            </div>
        </nav>
    </div>


    <!--Filter button and functionality-->

    <table
        class="table"
        id="itemLister"
        data-toggle="table"
        data-show-columns="true"
        data-search="true"
        data-show-toggle="true"
        data-pagination="true"
        data-resizable="true"
        data-sortable="true"
        data-show-columns-toggle-all="true"
        data-click-to-select="true"
        data-buttons="buttons"
        style="border: 1px solid black;"
        <?php
        if(sizeof($view->items) == 0 ){
            echo "data-url='/json/data.json'";
        }
        ?>
    >
        <thead>
        <tr>
            <th data-checkbox="true"></th>
            <?php
            foreach($view->fields as $field){
                if(in_array($field, $view->defaultFields)){
                    echo "<th data-field='$field' scope='col' data-sortable='true'>$field</th>";
                }else {
                    echo "<th data-field='$field' scope='col' data-sortable='true' data-visible='false'>$field</th>";
                }
            }
            ?>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach($view->items as $item){
            echo "<tr><td data-checkbox='false'></td>";
            foreach($view->fields as $field){
                echo "<td>" . $item[$field] . "</td>";
                echo '<td> '.'<a href="/controllers/leftPanel.php'.$item[$field].'">'.$item[$field].'</a></td>';
            }
            echo "</tr>";
        }
        ?>
        </tbody>
    </table>
    <script>
        function buttons(){
            return {
                filterButton: {
                    text: 'Filter Results',
                    icon: 'bi-funnel-fill',
                    event: function () {
                        //code to open filter panel
                    },
                    attributes: {
                        title: 'Filter button'
                    }
                }
            }
        }
    </script>
</div>
</div>
<?php require_once $_SERVER['DOCUMENT_ROOT'] . "/views/template/footer.phtml";
