



    <div class="text-center pt-0">
    <button class="btn rounded-pill" style="background-color: #D4D4D4" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        Quick Access Menu <i class="bi bi-chevron-down"></i>
    </button>
    </div>
    <div class="collapse" id="collapseExample">
        <div class="d-flex justify-content-around">
            <div class="card p-2" style="width:18rem">
                <a href="#" class="card-link text-decoration-none text-black"><i class="bi bi-bar-chart-line-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                <div class="card-text">
                  <h4 class="card-title">Generate Report</h4>
                  <p>Generate a report based on your chosen data.</div>
                </a>
                </div>
            <div class="card p-2" style="width:18rem">
                <a href="#" class="card-link text-decoration-none text-black"> <i class="bi bi-pencil-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                <div class="card-text">
                  <h4 class="card-title">Apply Discount</h4>
                  <p>Apply discount to your chosen items.</p>
                </div></a>
            </div>
            <div class="card p-2" style="width:18rem">
                <a href="#" class="card-link text-decoration-none text-black"><i class="bi bi-cash-coin" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                <div class="card-text">
                  <h4 class="card-title">Change Price</h4>
                  <p>Change the price of your chosen items.</p>
                </div></a>
            </div>
        </div>
    </div>



<?php require_once $_SERVER['DOCUMENT_ROOT'] . "/views/itemLister.phtml";