



    <!--Buttons-->
    <div class=" pt-0">
        <button type="button" class="btn rounded-pill" style="background-color: #D4D4D4;border: 1px solid black" data-bs-toggle="modal" data-bs-target="#exampleModal">
            User Dashboard
        </button>
    <button class="btn rounded-pill" style="background-color: #D4D4D4;border: 1px solid black" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        Quick Access Menu <i class="bi bi-chevron-down"></i>
    </button>

    </div>
    <!--Quick access toolbar content-->
    <div class="collapse pt-2 pb-2" style="background-color: #D4D4D4" id="collapseExample">
        <div class="d-flex justify-content-around">
            <div class="card p-2" style="width:25%; border: 1px solid black"> <!--Just changed width:14rem to 25%-->
                <a href="#" class="card-link text-decoration-none text-black"><i class="bi bi-bar-chart-line-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                <div class="card-text">
                  <h4 class="card-title">Generate Report</h4>
                  <p>Generate a report based on your chosen data.</div>
                </a>
                </div>
            <div class="card p-2" style="width:25%;border: 1px solid black"> 
                <a href="#" class="card-link text-decoration-none text-black"> <i class="bi bi-pencil-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                <div class="card-text">
                  <h4 class="card-title">Apply Discount</h4>
                  <p>Apply discount to your chosen items.</p>
                </div></a>
            </div>
            <div class="card p-2" style="width:25;border: 1px solid black">
                <a href="#" class="card-link text-decoration-none text-black"><i class="bi bi-cash-coin" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                <div class="card-text">
                  <h4 class="card-title">Change Price</h4>
                  <p>Change the price of your chosen items.</p>
                </div></a>
            </div>
        </div>
    </div>


    <!-- Dashboard -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="exampleModalLabel">User Dashboard</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <!--Dashboard content-->
                <div class="modal-body">
                    <div class="modal-body">
                        <div class="card-wrapper">
                            <div class="row">
                                <div class="col-4"">
                                    <a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
                                        <div class="card"> <!--Card container-->
                                            <i class="bi bi-pencil-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                                            <div class="card-text">
                                                <h3 class="card-title">Register new user</h3>
                                                <p>Create user and assign privileges</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-4""><a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
                                        <div class="card"> <!--Card container-->
                                            <i class="bi bi-layout-text-sidebar" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                                            <div class="card-text">
                                                <h3 class="card-title">Create a template</h3>
                                                <p>Create filtering template for left side panel and list display options</p>
                                            </div>
                                        </div>
                                    </a></div>
                                <div class="col-4"><a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
                                        <div class="card"> <!--Card container-->
                                            <i class="bi bi-hand-thumbs-down-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                                            <div class="card-text">
                                                <h3 class="card-title">Manage filters</h3>
                                                <p>Sort top 100 games by downloaded at the moment</p>
                                            </div>
                                        </div>
                                    </a></div>
                            </div>
                            <div class="row">
                                <div class="col-4"><a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
                                        <div class="card"> <!--Card container-->
                                            <i class="bi bi-heart-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                                            <div class="card-text">
                                                <h3 class="card-title">Top rated</h3>
                                                <p>Sort top 100 games by top rated at the moment</p>
                                            </div>
                                        </div>
                                    </a></div>
                                <div class="col-4"><a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
                                        <div class="card"> <!--Card container-->
                                            <i class="bi bi-star-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                                            <div class="card-text">
                                                <h3 class="card-title">Most popular</h3>
                                                <p>Sort top 100 games by most popular at the moment</p>
                                            </div>
                                        </div>
                                    </a></div>
                                <div class="col-4"><a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
                                        <div class="card"> <!--Card container-->
                                            <i class="bi bi-hand-thumbs-down-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                                            <div class="card-text">
                                                <h3 class="card-title">Least downloaded</h3>
                                                <p>Sort top 100 games by least downloaded at the moment</p>
                                            </div>
                                        </div>
                                    </a></div>
                            </div>
                            <div class="row">
                                <div class="col-4"><a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
                                        <div class="card"> <!--Card container-->
                                            <i class="bi bi-heart-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                                            <div class="card-text">
                                                <h3 class="card-title">Top rated</h3>
                                                <p>Sort top 100 games by top rated at the moment</p>
                                            </div>
                                        </div>
                                    </a></div>
                                <div class="col-4"><a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
                                        <div class="card"> <!--Card container-->
                                            <i class="bi bi-star-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                                            <div class="card-text">
                                                <h3 class="card-title">Most popular</h3>
                                                <p>Sort top 100 games by most popular at the moment</p>
                                            </div>
                                        </div>
                                    </a></div>
                                <div class="col-4"><a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
                                        <div class="card"> <!--Card container-->
                                            <i class="bi bi-hand-thumbs-down-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                                            <div class="card-text">
                                                <h3 class="card-title">Least downloaded</h3>
                                                <p>Sort top 100 games by least downloaded at the moment</p>
                                            </div>
                                        </div>
                                    </a></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>



<?php require_once $_SERVER['DOCUMENT_ROOT'] . "/views/itemLister.phtml";
