<?php
if(isset($_GET['cards'])){
    echo '
<div id="toolbar" class="d-flex justify-content-start align-items-center" style="margin-left: 8vh" >
    <button class="btn btn-secondary mx-1" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"><i class="bi bi-funnel-fill"></i></button>
        <a class="btn btn-secondary mx-1" href="?" style="color: white"><i class="bi bi-list-task"></i></a></div>
    ';
}else{
    echo '
<div id="toolbar">
    <button class="btn btn-secondary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"><i class="bi bi-funnel-fill"></i></button>
        <a class="btn btn-secondary" href="?cards=true" style="color: white"><i class="bi bi-grid-fill"></i></a></div>';
}
