<link href="/css/bootstrap/bootstrap.css" rel="stylesheet">
<!--Bootstrap Icons-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<!--Created (or modified) CSS file-->
<link rel="stylesheet" type="text/css" href="../css/styles.css" />

<section class="container all-cards"> <!--A container that contains the headline and the cards-->

    <h1>Quick Access</h1> <!--The headline-->

    <div class="card-wrapper"> <!--The container that wraps(contains) all the cards-->

        <a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
            <div class="card"> <!--Card container-->
                <i class="bi bi-bar-chart-line-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                <div class="card-text">
                    <h3 class="card-title">Generate Report</h3>
                    <p>Generate a report based on your chosen data.</div>
            </div>
        </a>

        <a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
            <div class="card"> <!--Card container-->
                <i class="bi bi-pencil-fill" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                <div class="card-text">
                    <h3 class="card-title">Apply Discount</h3>
                    <p>Apply discount to your chosen items.</p>
                </div>
            </div>
        </a>

        <a href="#" class="card-link"> <!--Anchor contains a single card to make the card clickable-->
            <div class="card"> <!--Card container-->
                <i class="bi bi-cash-coin" style="font-size:50px;"></i> <!--Bootstrap icon modified in css file-->
                <div class="card-text">
                    <h3 class="card-title">Change Price</h3>
                    <p>Change the price of your chosen items.</p>
                </div>
            </div>
        </a>
    </div>
</section>

<?php require_once $_SERVER['DOCUMENT_ROOT'] . "/views/itemLister.phtml";