
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/js/jquery-3.6.0.min.js" type="text/javascript"></script>
    <!-- BootStrap JS -->
    <script src="/js/bootstrap.bundle.js" type="text/javascript"></script>
    <!--    BootstrapTable-->
    <script src="https://unpkg.com/jquery-resizable-columns@0.2.3/dist/jquery.resizableColumns.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/extensions/resizable/bootstrap-table-resizable.min.js"></script>
    </div>
    <p class="d-flex justify-content-around ">Created by Group 4 Hack Camp University of Salford, 2022</p>
</body>
</html>