
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/js/jquery-3.6.0.min.js" type="text/javascript"></script>
    <!-- BootStrap JS -->
    <script src="/js/bootstrap.bundle.js" type="text/javascript"></script>
    <!--    BootstrapTable-->
    <script src="https://unpkg.com/jquery-resizable-columns@0.2.3/dist/jquery.resizableColumns.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/extensions/resizable/bootstrap-table-resizable.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/extensions/toolbar/bootstrap-table-toolbar.min.js"></script>

    </div>
    <p class="d-flex justify-content-around ">Created by Group 4 Hack Camp University of Salford, 2022</p>

    <script>
        $(document).ready( function (){

            $('.dsp-btn').click(function (e) {
                e.preventDefault();
               var app_id = $(this).closest('.app').find('.app-id').text();


                $.ajax({
                   type: "POST",
                   url:"/controllers/moreDetailsPopup.php",
                    data: {
                       'checking-view-btn':true,
                        'app-id':app_id,
                    },
                    success: function (response){
                       $('.details-view-data').html(response);
                       $('#itemDetailsModal').modal('show');
                    }

                });

            });

        });

    </script>

    </body>
</html>